# Generated by Django 3.2.9 on 2021-11-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('speciality', models.CharField(max_length=200, verbose_name='Специализация')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('content', models.TextField(blank=True, verbose_name='Отчёт')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикаций')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='статус')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmos.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_date'],
            },
        ),
    ]
